apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers  \n  - system:nodes  \n  rolearn:
    arn:aws:iam::698276521298:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-146V8GLCVWYWS\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::698276521298:role/UdacityFlaskDeployCBKubectlRole  \n
    \ username: build  \n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-28T12:24:05Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-28T12:24:05Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-02-28T13:34:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "13303"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 00e60f4b-7878-4969-8743-3e8a686382fa
